# Generated by Django 4.0.3 on 2023-05-16 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_point_linestring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linestring',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_strings', to='Auth.point'),
        ),
    ]
