# Generated by Django 4.0.3 on 2023-05-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_linestring_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineString',
        ),
    ]
