# Generated by Django 4.0.3 on 2023-05-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_delete_linestring'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_segments', to='Auth.point')),
                ('linestring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.linestring')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_segments', to='Auth.point')),
            ],
        ),
    ]
