# Generated by Django 4.0.3 on 2023-05-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_linestring_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='end_point',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='start_point',
        ),
    ]
