# Generated by Django 4.0.3 on 2023-05-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_remove_segment_end_point_remove_segment_start_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Segment',
        ),
    ]
