# Generated by Django 4.0.3 on 2023-05-17 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_delete_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('start_latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('end_longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('end_latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('name', models.CharField(max_length=255)),
                ('linestring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.linestring')),
            ],
        ),
    ]
