# Generated by Django 4.0.3 on 2023-05-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0015_remove_segment_linestring_delete_linestring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('start_latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('end_longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('end_latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('name', models.CharField(max_length=255)),
                ('linestring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.linestring')),
            ],
        ),
        migrations.AddField(
            model_name='linestring',
            name='points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linestrings', to='Auth.point'),
        ),
    ]
