# Generated by Django 4.0.3 on 2023-05-19 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0018_linestring_point_segment_linestring_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.segment')),
            ],
        ),
    ]
