# Generated by Django 4.0.3 on 2023-05-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0019_waterlevel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterLevel',
        ),
    ]
