# Generated by Django 4.0.3 on 2023-05-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0023_notification_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temprature', models.CharField(blank=True, max_length=255, null=True)),
                ('weather', models.FloatField(blank=True, max_length=255, null=True)),
                ('Humidity', models.FloatField(blank=True, max_length=255, null=True)),
                ('Pressure', models.FloatField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.segment')),
            ],
        ),
    ]
