# Generated by Django 4.0.3 on 2023-05-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0024_parametre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parametre',
        ),
    ]
