# Generated by Django 4.0.3 on 2023-05-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0025_delete_parametre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('Temprature', models.CharField(blank=True, max_length=255, null=True)),
                ('pression', models.FloatField(blank=True, null=True)),
                ('taux_humidite', models.FloatField(blank=True, null=True)),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.point')),
            ],
        ),
    ]
