# Generated by Django 4.0.3 on 2023-06-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0026_parametre'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='segment',
            name='fuite',
            field=models.BooleanField(default=False),
        ),
    ]
